### ISSUE TITLE
Can't get this to work on ST3 (OSX)

### ISSUE THREAD

**Issue by tott** [noahcoad/open-url#13]
Thanks for the great plugin. I was using it on ST2 and liked it a lot, sadly on ST3 the command does not do anything for me. 
I see the menus and all seems to be fine but the browser never opens.
I tried on the console using

> > > import webbrowser
> > > webbrowser.open_new_tab('http://google.com')

which works fine. But 

> > > view.run_command('open_url')

does not do anything as does hitting the "Open Url" command from the context menu.

Do you have any clue what might be the issue?

**Comment by noahcoad** [comment]
working now?  I use mine entirely on ST3 on OSX

**Comment by kylebebak** [comment]
This is now working, if the issue persists please reopen.
