### ISSUE TITLE
Google search

### ISSUE THREAD

**Issue by maliayas** [noahcoad/open-url#18]
It may not be a good idea. It causes you to give your private strings to google if it is unknown by the plugin.

I think web search is a standalone scope that must be left to another plugin and another keybinding.

I propose:

``` diff
-               url = "http://google.com/#q=" + urllib.parse.quote(url, '')
-               webbrowser.open_new_tab(url)
+               print("open_url: URL/Path not understood")
```

**Comment by kylebebak** [comment]
@maliayas 

Hey, __web_searchers__ are now configurable in settings! The default web searcher, Google search, is just one of these web searchers. If you want get rid of it, add this to your Open URL settings:

```
"web_searchers": [],
```
