### ISSUE TITLE
add search path(s)

### ISSUE THREAD

**Issue by ginader** [noahcoad/open-url#23]
Feature request:
I love this extension and I can use if for a lot of my projects. Some of them don't work though because the linked files don't live in the same directory locally than later on the server. For those cases it would be great if we could add additional search paths in the settings where the script could look for the linked files.
Example in a html file in the root folder:
<link rel="stylesheet" href="/css/all.css" />
The css folder lives in a subfolder "www" so the path to find it would be "www/css/all.css" but of course it can't find it. Adding "www" as a default search path would solve this for me and probably others too. 
What do you think?

**Comment by noahcoad** [comment]
neat!  i like the idea of it being a user setting
would you like to code the change and submit a pull request?

**Comment by kylebebak** [comment]
@ginader 

This would be trivial to add, but I'm not sure it makes sense.

The files you're interested in for a given Sublime Text project are usually local to that project. Those that aren't, like dotfiles in the user's home directory, are local to the `~` alias. In other words, **Open URL** also handles URLs like `~/.gitignore_global`.

Can you show me any examples of search paths you'd like to use?

**Comment by noahcoad** [comment]
As I think of this more as well, I've been more careful to use relative paths in my projects.  I think we should close this request for now, unless its +1 by other community members or the original requester comes back with more details
