### ISSUE TITLE
MultiMarkdown Link support

### ISSUE THREAD

**Issue by floscr** [noahcoad/open-url#26]
It would be great if you added [MultiMarkdown](http://fletcherpenney.net/multimarkdown/) support.

Basically links get written like this:

```
[link title]

[link title]: http://www.somelink.com
```

which makes Text ways more readable with long URLs

**Comment by jbshirk** [comment]
If this underlined existing local URIs blue, and missing, red, this would practically become a markdown wiki.

https://github.com/noahcoad/open-url/issues/28

**Comment by kylebebak** [comment]
@floscr 

Delimiters are now configurable! See the **delimiters**  option in settings. The default delimiters are ``` \t\n\r\"'`,*<>[](){}```.

In other words, you can open URLs like this one just fine:

~~~
[link to](github.com)
~~~

**Comment by eugenesvk** [comment]
If my cursor (`___`) is at the first `[url name]`, how do I tweak the delimiters to open the url the name refers to?

```
[___link title]

[link title]: http://www.somelink.com
```
or 
`[___link title]: http://www.somelink.com`
