### ISSUE TITLE
Use custom browser in st2 and ubuntu + url wrapped in arbitrary symbols

### ISSUE THREAD

**Issue by simov** [noahcoad/open-url#29]
I was about to submit a PR but this package doesn't seems to be actively maintained, so here are two fixes that might help someone.
### Use custom browser in st2 and ubuntu

This package was opening my links with st2 in FF even though I have Chrome set as default browser on Ubuntu. So I stumbled upon [this thread](http://stackoverflow.com/questions/22445217/python-webbrowser-open-to-open-chrome-browser) and I edited my `/home/[USER]/.config/sublime-text-2/Packages/Open URL/open_url.py`

``` py
else:
  wb = webbrowser.get('/usr/bin/google-chrome %s')
  if "://" in url:
    wb.open_new_tab(url)
  elif re.search(r"\w[^\s]*\.(?:com|co|uk|gov|edu|tv|net|org|tel|me|us|mobi|es|io)[^\s]*\Z", url):
    if not "://" in url:
      url = "http://" + url
    wb.open_new_tab(url)
  else:
    url = "http://google.com/#q=" + urllib.quote(url, '')
    wb.open_new_tab(url)
```

This one opens up the links in Chrome on Linux. Of course that's hardcoded but I'm pretty sure you can figure out how to modify it to work with your own OS and browser.
### URL wrapped in arbitrary symbols

This is how you can strip any symbols that your url is wrapped with:

``` py
# strip quotes if quoted
if (url.startswith("\"") & url.endswith("\"")) | (url.startswith("\'") & url.endswith("\'")) | (url.startswith("`") & url.endswith("`")):
```

The added bits are 

``` py
| (url.startswith("`") & url.endswith("`"))
```

So for example you can add

``` py
 | (url.startswith("{") & url.endswith("}"))
```

for links wrapped like this {http://some.url} and so on.

**Comment by kylebebak** [comment]
Hey @simov , this issue is fixed in 1.1.0. You can set`delimiters` in your settings to tell the plugin when to stop automatically expanding the selection. 

The default delimiters are ``` \t\n\r\"'`,*<>[]()```. All the characters you mentioned above are included!
