### ISSUE TITLE
"google it" is custom and "url" is other encode

### ISSUE THREAD

**Issue by guohuihot** [noahcoad/open-url#31]
URL can be customized and it's also the same as encoding

（url = self.config.get('url') + urllib.quote(url.encode('utf8'), '')）

![qq](https://cloud.githubusercontent.com/assets/3119995/10095216/9b7b4262-639a-11e5-95d3-23d383560812.jpg)

![qq](https://cloud.githubusercontent.com/assets/3119995/10095276/225a7ad2-639b-11e5-807d-37fddc32e666.jpg)

**Comment by kylebebak** [comment]
@guohuihot 

Hey there! This is now possible, you can configure __web_searchers__ in your settings file. You can also specify the `encoding` for each web searcher.

The default web searcher is Google. It's configured as follows:

```
{ "label": "google search", "url": "http://google.com/search?q=", "encoding": "utf-8" }
```

You can add another one for Baidu or anything else if you want to.
