### ISSUE TITLE
Can the config be set on the User Preferences.sublime-settings?

### ISSUE THREAD

**Issue by medifle** [noahcoad/open-url#32]
For now I have no idea how to set default action for specific file extensions

**Comment by vegar** [comment]
This is the way of setting default action for specific file extensions:

* Copy [open_url.sublime-settings](https://github.com/noahcoad/open-url/blob/st3/open_url.sublime-settings) to your user folder
  * `Preferences->Browse Packages...` will take you to the package folder. 
  * Your user folder is the `User` subfolder
* Edit the content of the settings file as wanted
  * The default file includes some instructions to get you started

**Comment by kylebebak** [comment]
@vegar 
Thanks for explaining this!

You can also open the settings by pressing <kbd>shift+cmd+p</kbd> to open the Command Palette, then looking for __Open URL__.
