### ISSUE TITLE
How to setup custom hotkey for edit file?

### ISSUE THREAD

**Issue by max-mykhailenko** [noahcoad/open-url#34]
I want to open file for edit without dropdown menu. How I can do that? Custom keybinding with argument will be cool.

**Comment by kylebebak** [comment]
@max-mykhailenko 

I like this idea, I'll work on it today.

**Comment by kylebebak** [comment]
Ok, it's done.

You can now skip the menu for opening files (defaults to edit in Sublime Text) and folders (defaults to reveal in Finder).

If you're running OSX, you could do this by adding the following to your key bindings:

```
{ "keys": ["ctrl+alt+u"], "command": "open_url", "args": { "show_menu": false } },
```
