### ISSUE TITLE
[feature request] Set default browser option?

### ISSUE THREAD

**Issue by fabianmoronzirfas** [noahcoad/open-url#38]
Out of the blue the package startet using Firefox for opening urls under the cursor even though my default browser is chrome. Any suggestions how to change this or how to set the default browser for the package?

**Comment by coodoo** [comment]
Same here, would really love to have the freedom of using designated browser instead!

**Comment by coodoo** [comment]
bump?

**Comment by PaulCapestany** [comment]
Ditto... I (seemingly) randomly had Sublime start using Safari instead of Chrome, and it's been driving me nuts!

**Comment by fabianmoronzirfas** [comment]
Looks like with the new version of ST3 this is fixed. Still it would be nice to have the possibility to select the browser.

**Comment by kylebebak** [comment]
Going to work on this today!

**Comment by kylebebak** [comment]
Done! In 1.3.0, you can specify the web browser used to open new tabs with the __web_browser__ setting.

__web_browser__ can be an empty string, or a string [from this list](https://docs.python.org/3.3/library/webbrowser.html). If it's an empty string, the "default browser" will be used. I don't know how Python determines which browser this is, but for me it's Chrome.

@fabianmoronzirfas 
Thanks for creating this issue, this is a useful feature

**Comment by fabianmoronzirfas** [comment]
Cool. I must confess I walked a way from Sublime Text and am now using VSCode
