### ISSUE TITLE
Settings file could not be opened

### ISSUE THREAD

**Issue by skylogic004** [noahcoad/open-url#40]
When I go to "Open URL: Settings" I get this error message:

> The settings file "res://Packages/open-url/open_url.sublime-settings" could not be opened

I've never tried to go into Open URL's settings before so I don't know how long this problem has existed.

Running on Windows 7, Sublime 3.1.1, latest open-url version.

**Comment by kylebebak** [comment]
@skylogic004 

This should be fixed now. It stemmed from a confusion of mine regarding repository name vs package name.

Please try opening the settings and let me know what happens. Thanks!
