### ISSUE TITLE
Sadly the new version broke the functionality I was using

### ISSUE THREAD

**Issue by DmitriyK-CPKIO** [noahcoad/open-url#41]
I used to open links like `consultantplus://offline/ref=134676DEC6826BFB6C6B4FF2F462E22F025B0C7F0C13B0BE7210BF43DF6E8C91F6E2EE0CA63EB0A6DAM1yBO` via this plugin, but now it asks me to fix or google it.

**Comment by kylebebak** [comment]
Can you explain what used to happen when you opened this URL with the plugin?

Did this open in your browser? Or in the file system?

**Comment by DmitriyK-CPKIO** [comment]
Previously this link was opened in an external program (legal database) without any questions asked. Now it shows me a dialog to modify this link or open in a browser.

**Comment by kylebebak** [comment]
Hey there!

I added a setting called `other_custom_commands`, which allows you to pass special URLs that are neither files, folders, nor web URLs to the shell command of your choosing.

You can match these URLs using regular expressions. Here's an example for opening an FTP URL in the FTP client FileZilla.

~~~json
"other_custom_commands": [
    { "label": "open with filezilla", "pattern": "^ftp://", "commands": [ "open", "-a", "/Applications/FileZilla.app" ] },
  ],
~~~

Run **Open URL: Settings** from the Command Palette, and add a something similar to what I've shown you above, but change the regex to match "^consultantplus://", and choose an appropriate application to open it with.

I'm going to close this issue. If you have trouble let me know.

**Comment by DmitriyK-CPKIO** [comment]
I still cant get this to work. The URLs are registered in the system, the command line should be `cons.exe /url "%1"`.

I would like the behaviour would stay the same it was before.

**Comment by kylebebak** [comment]
That ship has sailed, but you should be able to get this to work with the current behavior.

Try opening your Python 3 shell, and run the following:

~~~py
import subprocess

subprocess.check_call(['C:\Path\To\ConsultantPlus.exe', 'consultantplus://offline/ref=134676DEC6826BFB6C6B4FF2F462E22F025B0C7F0C13B0BE7210BF43DF6E8C91F6E2EE0CA63EB0A6DAM1yBO'], shell=False)
~~~

Of course you should replace `C:\Path\To\cons.exe` with the correct path to the executable for ConsultantPlus. If this works in your Python shell, it will also work using Open URL.

You can just paste the following into your settings:

~~~json
"other_custom_commands": [
    { "label": "open with consultant plus", "pattern": "^consultantplus://", "commands": [ "C:\Path\To\cons.exe" ] },
  ],
~~~
~~~

**Comment by DmitriyK-CPKIO** [comment]
Your way it runs, once. And subsequent links cannot be opened because the system cannot have tho copies of the `cons.exe` running. So its a dead end.

But I got i figured out:

> subprocess.check_call(['start', 'consultantplus://offline/ref=134676DEC6826BFB6C6B4FF2F462E22F025B0C7F0C13B0BE7210BF43DF6E8C91F6E2EE0CA63EB0A6DAM1yBO'], shell=**True**)

 works as expected. Can shell parameted be passed to your plugin?

**Comment by kylebebak** [comment]
Ok, it seems like we're making progress.

Currently, there's no way to to specify other arguments to `subprocess.check_call`, but it seems like it would be a good thing to configure via settings.

I'll add a `kwargs` param to custom_commands, so you can specify whichever kwargs you want, including `shell=True`, and I'll add examples on how to do this to the docs.

I'll reopen this and close it once I've pushed the change.

**Comment by kylebebak** [comment]
It's in prod now!

Try the following:

~~~json
"other_custom_commands": [
    { "label": "open with consultant plus", "pattern": "^consultantplus://", "commands": ["start"], "kwargs": {"shell": true} },
  ],
~~~

Please let me know if this works. If it doesn't I'll reopen the PR.

**Comment by DmitriyK-CPKIO** [comment]
It works good enough. It seems I can't skip the menu (with only one choice in it, obviously) when opening this kind of links. Using «OpenURL: Skip Menu» does nothing.

**Comment by kylebebak** [comment]
@DmitriyK-CPKIO 
>It seems I can't skip the menu

Thanks for noticing that, that's a small bug that I just fixed. Please let me know if you can skip the menu now.
