### ISSUE TITLE
Bug: 3x "reveal" on open folder

### ISSUE THREAD

**Issue by noahcoad** [noahcoad/open-url#44]
On OSX, when executing open-url on a folder, like ~/tmp the "reveal" menu option appears three times:
![repro](https://content.screencast.com/users/NoahCoad/folders/Jing/media/b67bb674-0e6b-4d60-80d0-12a71321af07/00000122.png)

**Comment by kylebebak** [comment]
Thanks for pointing this bug out!

I just fixed it, and will push a new version today.
