### ISSUE TITLE
feature_request(enhancement): templates support

### ISSUE THREAD

**Issue by Kristinita** [noahcoad/open-url#49]
### 1. Summary

It would be nice, if Open URL will open files, if templates used.

For example, **if**:

```html
<link rel="stylesheet" href="{{SITEURL}}/{{THEME_STATIC_DIR}}/css/general/basic.min.css">
```

Would be possible open file `./theme/css/general/basic.min.css`.

### 2. Argumentation

[**Template engines**](https://en.wikipedia.org/wiki/Comparison_of_web_template_engines) used everywhere. For example, Jinja2 syntax as in example above I use in [**Django**](https://www.djangoproject.com/) and [**Pelican**](https://blog.getpelican.com/) projects.

It would be nice to have quick navigation between project files, if templates used.

### 3. Example of expected behavior

Would be possible:

#### 3.1. Set of templates

`User/open_url.sublime-settings`:

```json
{
    "templates_paths": [{
        "D:\\Kristinita\\pelicanvariables.yaml"
    }
    ]
}
```

Open URL will take variables from [**`pelicanvariables.yaml` file**](https://github.com/Kristinita/KristinitaPelican/blob/master/pelicanvariables.yaml).

YAML syntax must be support.

#### 3.2. Custom templates

`User/open_url.sublime-settings`:

```json
{
    "custom_templates": [{
        "\\{\\{SITEURL\\}\\}: "\\.",
        "\\{\\{THEME_STATIC_DIR\\}\\}": "theme"
    }
    ]
}
```

Thanks.

**Comment by kylebebak** [comment]
Hey, sorry for not responding until now.

This is a nice idea, and I know it would be useful to a lot of developers. It's similar in spirit to #50 , and I think I might do them both this weekend.

3.1 is definitely out of scope. There are **many** templating engines out there, with no standard format, so building something that would handle `pelicanvariables.yaml` doesn't make sense.

However, I like 3.2. The setting could be something like `aliases`, and it would point to a dict with a list of mappings from aliases to their real, substituted value, pretty much just like you've written it above.

This would definitely be a per-project setting. Having global aliases that get applied to every project really doesn't make sense.

**Comment by kylebebak** [comment]
Ok, `aliases` has been added in 2.6.0.

Have a look at <https://github.com/noahcoad/open-url/#url--path-transforms>. You can set aliases globally in `Packages/User/open_url.sublime-settings`, or in any `.sublime-project` file, so these aliases only apply to one project.

[Have a look here to see how per-project settings work](https://github.com/noahcoad/open-url/#project-specific-settings).

Going to close this, let me know if you have any questions.

**Comment by Kristinita** [comment]
**Status: CONFIRMED** :heavy_check_mark:

Thanks.
